/* Automatically generated by po2tbl.sed from authforce.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"\
usage: %s [OPTION]... URL\n\
\n", 2},
  {"options:\n", 3},
  {"\
\t-b,\t--beep\t\t\tbeep when a match is found\n\
\t-d,\t--debug=NUMBER\t\t\tlevel of debugging\n\
\t\t--dummy-file=FILE\tfile containing dummy matches\n\
\t\t\t\t\t[username:password form]\n\
\t-h,\t--help\t\t\tdisplay this help and exit\n\
\t-l,\t--logfile=FILE\t\tset logfile to FILE\n\
\t-r,\t--resume[=FILE]\t\tresume old session using FILE\n\
\t\t\t\t\t[default session.save]\n\
\t-s,\t--save[=FILE]\t\tsave session on SIGUSR1 to FILE\n\
\t\t\t\t\t[default session.save]\n\
\t-c,\t--max-connects=NUMBER\tdon't make more than NUMBER connections\n\
\t-u,\t--max-users=NUMBER\tdon't try more than NUMBER users\n\
\t-U,\t--user-agent=STRING\tset user agent to STRING\n\
\t\t--pairs-file=FILE\tfile containing username:password pairs\n\
\t\t--password-delay=NUMBER\tdelay for # seconds between attempts\n\
\t\t--password-file=FILE\tfile containing common passwords\n\
\t-p,\t--path=STRING\t\tlook for pathlist STRING\n\
\t-P,\t--proxy=STRING\t\tset proxy to STRING\n\
\t-q,\t--quiet\t\t\tdon't output to stdout\n\
\t\t--user-delay=NUMBER\tdelay for # seconds between usernames\n\
\t\t--username-file=FILE\tfile containing list of usernames\n\
\t\t--verbose\t\tbe verbose (default), opposite of --quiet\n\
\t-V,\t--version\t\tprint version information and exit\n", 4},
  {"\
\n\
Report bugs to <%s>.\n", 5},
  {"%s: Missing arguments\n", 6},
  {"Try %s --help for more information.\n", 7},
  {"\
%s %s\n\
\n\
Copyright (C) 2000 %s\n\
There is NO warranty.  You may redistribute this software\n\
under the terms of the GNU General Public License.\n\
For more information about these matters, see the files named COPYING\n\
\n\
Written by %s <%s>.\n", 8},
  {"%s: missing URL\n", 9},
  {"\
Usage: %s [OPTION]... [URL]\n\
\n", 10},
  {"Try `%s --help` for more information.\n", 11},
  {"%s: too many URLs\n", 12},
  {"initialize_data: couldn't open %s\n", 13},
  {"scan started: %s", 14},
  {"scan ended: %s", 15},
  {"main: session_function greater than 1\n", 16},
  {"main: session_usernumber greater than num_lines\n", 17},
  {"main: session_count greater than num_lines\n", 18},
  {"match [%s:%s]\n", 19},
  {"max users reached at %i\n", 20},
  {"Congratulations: %i password%s found.\n", 21},
  {"No passwords found.\n", 22},
};

int _msg_tbl_length = 22;
